<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Niranjan" ignored="0" name="Test123" tests="1" failures="1" timestamp="17 Aug 2017 13:14:20 GMT" time="48.506" errors="0">
  <testcase name="testng" time="47.39" classname="com.testcases.CreateAccount">
    <failure type="java.lang.AssertionError" message="expected [Your Salesforce Account has been created successfully in DSM.] but found [Success:
Your Salesforce Account has been created successfully in DSM.]">
      <![CDATA[java.lang.AssertionError: expected [Your Salesforce Account has been created successfully in DSM.] but found [Success:
Your Salesforce Account has been created successfully in DSM.]
	at com.testcases.CreateAccount.testng(CreateAccount.java:84)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testng -->
</testsuite> <!-- Test123 -->
